name = "mde-prod"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "mde-prod"

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
# wrangler secret put GEMINI_API_KEY
